source 'https://rubygems.org'

ruby '2.0.0'

gem 'airbrake'
gem 'active_model_serializers'
gem 'bitters'
gem 'bourbon'
gem 'clearance'
gem 'delayed_job_active_record', '>= 4.0.0'
gem 'email_validator'
gem 'flutie'
gem 'high_voltage'
gem 'neat'
gem 'pg'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-timeout'
gem 'rails', '>= 4.1.6'
gem 'recipient_interceptor'
gem 'sass-rails', '~> 4.0.0'
gem 'simple_form'
gem 'sprockets', '2.11.0'
gem 'title'
gem 'uglifier'
gem 'unicorn'

group :development do
  gem 'foreman'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 2.0'
end

group :test do
  gem 'capybara-webkit', '>= 1.0.0'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'webmock'
end

group :staging, :production do
  gem 'rails_12factor'
  gem 'newrelic_rpm', '>= 3.7.3'
end
